version: "2"

networks:
  int_server:
    driver: bridge

services:
  mongo_s:
    build: ./mongodb
    container_name: int_mongo
    command: mongod
    volumes: 
      - ./mongodb/db:/data/db
    ports:
      - "37017:27017"
    networks:
      - int_server

  book_server:
    build: ./book_server
    container_name: int_go
    depends_on: 
      - mongo_s
      - redis_server
    ports:
      - "28001:80"
    networks:
      - int_server
      
  gate_server:
    build: ./gate_server
    container_name: int_gate
    depends_on: 
      - mongo_s
      - redis_server
    ports: 
      - "80:80"
    networks: 
      - int_server

  redis_server:
    image: redis:latest
    container_name: int_redis
    ports:
      - "6379:6379"
    networks: 
      - int_server
  
  
