version: "2"

networks:
  int_server:
    driver: bridge

services:
  mongo_s:
    build: ./mongodb
    container_name: int_mongo
    command: mongod
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "37017:27017"
    networks:
      - int_server

  book_server:
    build: ./book_server
    container_name: int_go
    volumes:
      - ./book_server:/book_server
      - ./boltdbs:/book_server/boltdbs
    depends_on:
      - mongo_s
      - redis_server
    ports:
      - "28001:80"
    networks:
      - int_server

  gate_server:
    build: ./gate_server
    container_name: int_gate
    volumes:
      - ./gate_server:/gate_server
      - ./boltdbs:/gate_server/boltdbs
    depends_on:
      - mongo_s
      - redis_server
    ports:
      - "28002:80"
    networks:
      - int_server

  redis_server:
    image: redis:alpine
    container_name: int_redis
    networks:
      - int_server

  id_server:
    build: ./identification
    container_name: id_server
    volumes:
      - ./identification:/id
    ports:
      - "12480:80"
    networks:
      - int_server
